<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?php echo $this->headTitle('Notes Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
        ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
    ?>
    <?php echo $this->headScript()
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js')
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js')
    ?>
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-blue layout-top-nav">
<div class="wrapper">
    <!-- Full Width Column -->
    <div class="content-wrapper">
        <div class="container">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Notes Application
                    <small>Version 1.0</small>
                </h1>

            </section>

            <!-- Main content -->
            <section class="content">
                <?php echo $this->content; ?>
                <!-- /.box -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.container -->
    </div>
</div>
<!-- ./wrapper -->

<?php $this->inlineScript()->appendFile('/plugins/jQuery/jQuery-2.2.0.min.js'); ?>
<?php $this->inlineScript()->appendFile('/bootstrap/js/bootstrap.min.js'); ?>
<?php $this->inlineScript()->appendFile('/plugins/slimScroll/jquery.slimscroll.min.js'); ?>
<?php $this->inlineScript()->appendFile('/plugins/fastclick/fastclick.js'); ?>
<?php $this->inlineScript()->appendFile('/dist/js/app.min.js'); ?>
<?php $this->inlineScript()->appendFile('/dist/js/demo.js'); ?>

<?php echo $this->inlineScript(); ?>
</body>
</html>
