<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>

        <h3 class="box-title">Add</h3>

    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php
        $form->setAttribute('action', $this->url('notes/add'));
        $form->setAttribute('method', 'post');
        $form->prepare();
        ?>

        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
        <?php echo $this->formRow($form->get('title')); ?>
        </div>
        <div class="form-group">
        <?php echo $this->formRow($form->get('description')); ?>
        </div>
        <div class="form-group">
        <?php echo $this->formRow($form->get('dueDate')); ?> (yyyy-mm-dd)
        </div>
        <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>