<?php
//$form->setAttribute('action', $this->url('notes/edit', ['id' => $id]));
$form->setAttribute('method', 'post');
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('description')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('dueDate')); ?> (yyyy-mm-dd)
</div>
<div class="form-group">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>